# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commentViewer.ui'
#
# Created: Sat Sep 10 12:41:28 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1249, 420)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Set Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.UserComboBox = QtGui.QComboBox(self.frame)
        self.UserComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.UserComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.UserComboBox.setObjectName(_fromUtf8("UserComboBox"))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(0, QtGui.QApplication.translate("Form", "not started", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(1, QtGui.QApplication.translate("Form", "started", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(2, QtGui.QApplication.translate("Form", "in progress", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(3, QtGui.QApplication.translate("Form", "proposed final", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(4, QtGui.QApplication.translate("Form", "final", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(5, QtGui.QApplication.translate("Form", "omit", None, QtGui.QApplication.UnicodeUTF8))
        self.UserComboBox.addItem(_fromUtf8(""))
        self.UserComboBox.setItemText(6, QtGui.QApplication.translate("Form", "delivered", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.UserComboBox, 1, 2, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout.addWidget(self.frame_2, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.textEdit = QtGui.QTextEdit(self.widget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.textEdit)
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LoadGroupBox = QtGui.QGroupBox(self.widget_2)
        self.LoadGroupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.LoadGroupBox.setTitle(QtGui.QApplication.translate("Form", "SEND COMMENT", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadGroupBox.setObjectName(_fromUtf8("LoadGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.LoadGroupBox)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sendPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.sendPushButton.setText(QtGui.QApplication.translate("Form", "SEND", None, QtGui.QApplication.UnicodeUTF8))
        self.sendPushButton.setObjectName(_fromUtf8("sendPushButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sendPushButton)
        self.checkBox = QtGui.QCheckBox(self.LoadGroupBox)
        self.checkBox.setText(QtGui.QApplication.translate("Form", "attach current image", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBox)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.LoadGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "DRAW", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Form", "select session", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.sendPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.sendComment)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

