# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dailiesViewer.ui'
#
# Created: Sun Dec 11 01:04:12 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(831, 426)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(500, 200))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setText(QtGui.QApplication.translate("Form", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.UserComboBox = QtGui.QComboBox(self.frame_4)
        self.UserComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.UserComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.UserComboBox.setObjectName(_fromUtf8("UserComboBox"))
        self.horizontalLayout.addWidget(self.UserComboBox)
        spacerItem1 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setText(QtGui.QApplication.translate("Form", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.SequComboBox = QtGui.QComboBox(self.frame_4)
        self.SequComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SequComboBox.setObjectName(_fromUtf8("SequComboBox"))
        self.horizontalLayout.addWidget(self.SequComboBox)
        spacerItem2 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(0, 0, 4, 0)
        self.formLayout_3.setHorizontalSpacing(2)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.refreshCombosPB = QtGui.QPushButton(self.frame)
        self.refreshCombosPB.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshCombosPB.setObjectName(_fromUtf8("refreshCombosPB"))
        self.gridLayout.addWidget(self.refreshCombosPB, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet(_fromUtf8(""))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 520, 369))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.frame_3 = QtGui.QFrame(self.widget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setContentsMargins(0, 0, 40, 0)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Thumbnail scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.thumbScale = QtGui.QSlider(self.frame_3)
        self.thumbScale.setMaximumSize(QtCore.QSize(300, 16777215))
        self.thumbScale.setOrientation(QtCore.Qt.Horizontal)
        self.thumbScale.setObjectName(_fromUtf8("thumbScale"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.thumbScale)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LoadGroupBox = QtGui.QGroupBox(self.widget_2)
        self.LoadGroupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.LoadGroupBox.setTitle(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadGroupBox.setObjectName(_fromUtf8("LoadGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.LoadGroupBox)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.LoadPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadPushButton.setText(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadPushButton.setCheckable(False)
        self.LoadPushButton.setObjectName(_fromUtf8("LoadPushButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LoadPushButton)
        self.LoadFpPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadFpPushButton.setText(QtGui.QApplication.translate("Form", "LOAD_FP", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadFpPushButton.setObjectName(_fromUtf8("LoadFpPushButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LoadFpPushButton)
        self.pushButton_2 = QtGui.QPushButton(self.LoadGroupBox)
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "LOAD PROXY", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton_2)
        self.DiskCachePushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.DiskCachePushButton.setText(QtGui.QApplication.translate("Form", "DISK CACHE", None, QtGui.QApplication.UnicodeUTF8))
        self.DiskCachePushButton.setObjectName(_fromUtf8("DiskCachePushButton"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.DiskCachePushButton)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.LoadGroupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "MANAGE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setContentsMargins(0, 2, 2, 2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.DeleteRenderPushButton = QtGui.QPushButton(self.groupBox_3)
        self.DeleteRenderPushButton.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteRenderPushButton.setCheckable(False)
        self.DeleteRenderPushButton.setObjectName(_fromUtf8("DeleteRenderPushButton"))
        self.verticalLayout_6.addWidget(self.DeleteRenderPushButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "REVIEW", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Form", "select session", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.sessionSelComboBox = QtGui.QComboBox(self.groupBox_2)
        self.sessionSelComboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.sessionSelComboBox.setObjectName(_fromUtf8("sessionSelComboBox"))
        self.verticalLayout_5.addWidget(self.sessionSelComboBox)
        self.refreshComboPushButton = QtGui.QPushButton(self.groupBox_2)
        self.refreshComboPushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.refreshComboPushButton.setText(QtGui.QApplication.translate("Form", "refreshList", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshComboPushButton.setObjectName(_fromUtf8("refreshComboPushButton"))
        self.verticalLayout_5.addWidget(self.refreshComboPushButton)
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "add to session", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_5.addWidget(self.pushButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.splitter)
        self.label_4.setBuddy(self.UserComboBox)
        self.label_2.setBuddy(self.SequComboBox)
        self.label_3.setBuddy(self.lineEdit)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.LoadPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.Load)
        QtCore.QObject.connect(self.refreshComboPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.refreshCal)
        QtCore.QObject.connect(self.DeleteRenderPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.DeleteDaily)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

