# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created: Sat Nov 26 23:33:22 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(562, 693)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.ident = QtGui.QWidget(self.splitter)
        self.ident.setEnabled(True)
        self.ident.setMaximumSize(QtCore.QSize(16777215, 300))
        self.ident.setObjectName(_fromUtf8("ident"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ident)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.ident)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Main Info", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setText(QtGui.QApplication.translate("Form", "shot name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.Shot_LineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.Shot_LineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Shot_LineEdit.setMaxLength(20)
        self.Shot_LineEdit.setObjectName(_fromUtf8("Shot_LineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.Shot_LineEdit)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(256, 256))
        self.graphicsView.setMaximumSize(QtCore.QSize(256, 256))
        self.graphicsView.setBaseSize(QtCore.QSize(0, 0))
        self.graphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graphicsView.setLineWidth(4)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.info = QtGui.QWidget(self.splitter)
        self.info.setEnabled(True)
        self.info.setObjectName(_fromUtf8("info"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.info)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.info)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Editorial", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Comp range", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("Form", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.CompInLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.CompInLineEdit.setObjectName(_fromUtf8("CompInLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.CompInLineEdit)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Out", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.CompOutLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.CompOutLineEdit.setObjectName(_fromUtf8("CompOutLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.CompOutLineEdit)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Cut Range", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("Form", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.CutInLineEdit = QtGui.QLineEdit(self.groupBox)
        self.CutInLineEdit.setObjectName(_fromUtf8("CutInLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.CutInLineEdit)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setText(QtGui.QApplication.translate("Form", "out", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.CutOutLineEdit = QtGui.QLineEdit(self.groupBox)
        self.CutOutLineEdit.setObjectName(_fromUtf8("CutOutLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.CutOutLineEdit)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.widget = QtGui.QWidget(self.info)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.StatusComboBox = QtGui.QComboBox(self.widget)
        self.StatusComboBox.setObjectName(_fromUtf8("StatusComboBox"))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(0, QtGui.QApplication.translate("Form", "To be started", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(1, QtGui.QApplication.translate("Form", "Started", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(2, QtGui.QApplication.translate("Form", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(3, QtGui.QApplication.translate("Form", "Final", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(4, QtGui.QApplication.translate("Form", "Omit", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusComboBox.addItem(_fromUtf8(""))
        self.StatusComboBox.setItemText(5, QtGui.QApplication.translate("Form", "Delivered", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4.addWidget(self.StatusComboBox)
        self.label = QtGui.QLabel(self.widget)
        self.label.setText(QtGui.QApplication.translate("Form", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.textEdit = Qsci.QsciScintilla(self.widget)
        self.textEdit.setToolTip(_fromUtf8(""))
        self.textEdit.setWhatsThis(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout.addWidget(self.splitter)
        self.label_8.setBuddy(self.Shot_LineEdit)
        self.label_5.setBuddy(self.CompInLineEdit)
        self.label_6.setBuddy(self.CompOutLineEdit)
        self.label_3.setBuddy(self.CutInLineEdit)
        self.label_4.setBuddy(self.CutOutLineEdit)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.Shot_LineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Form.save)
        QtCore.QObject.connect(self.CompInLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Form.save)
        QtCore.QObject.connect(self.CompOutLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Form.save)
        QtCore.QObject.connect(self.CutInLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Form.save)
        QtCore.QObject.connect(self.CutOutLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Form.save)
        QtCore.QObject.connect(self.StatusComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.save)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

from PyQt4 import Qsci
