# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flip.ui'
#
# Created: Sun Dec 11 13:38:57 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1197, 944)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.MainWidget = QtGui.QWidget(self.centralwidget)
        self.MainWidget.setObjectName(_fromUtf8("MainWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.MainWidget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.GLLayout = QtGui.QVBoxLayout()
        self.GLLayout.setObjectName(_fromUtf8("GLLayout"))
        self.verticalLayout_6.addLayout(self.GLLayout)
        self.InfoWidget = QtGui.QWidget(self.MainWidget)
        self.InfoWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.InfoWidget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.InfoWidget.setStyleSheet(_fromUtf8("background-color: rgb(0,0,0);\n"
"border: 1px solid;\n"
"border-top-color:  rgb(50,50,50);\n"
""))
        self.InfoWidget.setObjectName(_fromUtf8("InfoWidget"))
        self.gridLayout = QtGui.QGridLayout(self.InfoWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ExpLabel = QtGui.QLabel(self.InfoWidget)
        self.ExpLabel.setStyleSheet(_fromUtf8("color: rgb(150,150,150);"))
        self.ExpLabel.setText(QtGui.QApplication.translate("MainWindow", "Exp:", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpLabel.setObjectName(_fromUtf8("ExpLabel"))
        self.gridLayout.addWidget(self.ExpLabel, 3, 6, 1, 1)
        self.RLabel = QtGui.QLabel(self.InfoWidget)
        self.RLabel.setStyleSheet(_fromUtf8("color: rgb(200,0,0);"))
        self.RLabel.setText(QtGui.QApplication.translate("MainWindow", "R:", None, QtGui.QApplication.UnicodeUTF8))
        self.RLabel.setObjectName(_fromUtf8("RLabel"))
        self.gridLayout.addWidget(self.RLabel, 3, 7, 1, 1)
        self.GLabel = QtGui.QLabel(self.InfoWidget)
        self.GLabel.setStyleSheet(_fromUtf8("color: rgb(0,200,0);"))
        self.GLabel.setText(QtGui.QApplication.translate("MainWindow", "G:", None, QtGui.QApplication.UnicodeUTF8))
        self.GLabel.setObjectName(_fromUtf8("GLabel"))
        self.gridLayout.addWidget(self.GLabel, 3, 8, 1, 1)
        self.BLabel = QtGui.QLabel(self.InfoWidget)
        self.BLabel.setStyleSheet(_fromUtf8("color: rgb(0,0,200);"))
        self.BLabel.setText(QtGui.QApplication.translate("MainWindow", "B:", None, QtGui.QApplication.UnicodeUTF8))
        self.BLabel.setObjectName(_fromUtf8("BLabel"))
        self.gridLayout.addWidget(self.BLabel, 3, 9, 1, 1)
        self.LUTLabel = QtGui.QLabel(self.InfoWidget)
        self.LUTLabel.setStyleSheet(_fromUtf8("color: rgb(150,150,150);"))
        self.LUTLabel.setText(QtGui.QApplication.translate("MainWindow", "LUT:", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTLabel.setObjectName(_fromUtf8("LUTLabel"))
        self.gridLayout.addWidget(self.LUTLabel, 3, 3, 1, 1)
        self.ProjectLabel = QtGui.QLabel(self.InfoWidget)
        self.ProjectLabel.setStyleSheet(_fromUtf8("color: rgb(150,150,150);"))
        self.ProjectLabel.setText(QtGui.QApplication.translate("MainWindow", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.ProjectLabel.setObjectName(_fromUtf8("ProjectLabel"))
        self.gridLayout.addWidget(self.ProjectLabel, 3, 0, 1, 1)
        self.ShotLabel = QtGui.QLabel(self.InfoWidget)
        self.ShotLabel.setStyleSheet(_fromUtf8("color: rgb(150,150,150);"))
        self.ShotLabel.setLineWidth(0)
        self.ShotLabel.setText(QtGui.QApplication.translate("MainWindow", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.ShotLabel.setTextFormat(QtCore.Qt.RichText)
        self.ShotLabel.setMargin(0)
        self.ShotLabel.setObjectName(_fromUtf8("ShotLabel"))
        self.gridLayout.addWidget(self.ShotLabel, 3, 2, 1, 1)
        self.UserLabel = QtGui.QLabel(self.InfoWidget)
        self.UserLabel.setStyleSheet(_fromUtf8("color: rgb(150,150,150);"))
        self.UserLabel.setText(QtGui.QApplication.translate("MainWindow", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.UserLabel.setObjectName(_fromUtf8("UserLabel"))
        self.gridLayout.addWidget(self.UserLabel, 3, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.InfoWidget)
        self.verticalLayout.addWidget(self.MainWidget)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.firstFrameLineEdit = QtGui.QLineEdit(self.widget)
        self.firstFrameLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.firstFrameLineEdit.setObjectName(_fromUtf8("firstFrameLineEdit"))
        self.horizontalLayout.addWidget(self.firstFrameLineEdit)
        self.TimeLineSlider = QtGui.QSlider(self.widget)
        self.TimeLineSlider.setStyleSheet(_fromUtf8(""))
        self.TimeLineSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TimeLineSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.TimeLineSlider.setObjectName(_fromUtf8("TimeLineSlider"))
        self.horizontalLayout.addWidget(self.TimeLineSlider)
        self.lastFramelineEdit = QtGui.QLineEdit(self.widget)
        self.lastFramelineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lastFramelineEdit.setObjectName(_fromUtf8("lastFramelineEdit"))
        self.horizontalLayout.addWidget(self.lastFramelineEdit)
        self.lcdNumber = QtGui.QLCDNumber(self.widget)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 18))
        self.lcdNumber.setStyleSheet(_fromUtf8("background-color: rgb(30,30,30);\n"
"border-radius: 4px;"))
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.PlaypushButton = QtGui.QPushButton(self.widget)
        self.PlaypushButton.setMinimumSize(QtCore.QSize(60, 0))
        self.PlaypushButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.PlaypushButton.setObjectName(_fromUtf8("PlaypushButton"))
        self.horizontalLayout.addWidget(self.PlaypushButton)
        self.LoopPushButton = QtGui.QPushButton(self.widget)
        self.LoopPushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LoopPushButton.setText(QtGui.QApplication.translate("MainWindow", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.LoopPushButton.setObjectName(_fromUtf8("LoopPushButton"))
        self.horizontalLayout.addWidget(self.LoopPushButton)
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "LUT", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.LUTcomboBox = QtGui.QComboBox(self.widget)
        self.LUTcomboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.LUTcomboBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.LUTcomboBox.setObjectName(_fromUtf8("LUTcomboBox"))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "sRGB", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "rec709", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Film", None, QtGui.QApplication.UnicodeUTF8))
        self.LUTcomboBox.addItem(_fromUtf8(""))
        self.LUTcomboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.LUTcomboBox)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 21))
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.ColorCorrect = QtGui.QDockWidget(MainWindow)
        self.ColorCorrect.setMinimumSize(QtCore.QSize(0, 0))
        self.ColorCorrect.setBaseSize(QtCore.QSize(400, 0))
        self.ColorCorrect.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.ColorCorrect.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Grade", None, QtGui.QApplication.UnicodeUTF8))
        self.ColorCorrect.setObjectName(_fromUtf8("ColorCorrect"))
        self.Grade = colorCorrect()
        self.Grade.setObjectName(_fromUtf8("Grade"))
        self.ColorCorrect.setWidget(self.Grade)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ColorCorrect)
        self.ImageHub = QtGui.QDockWidget(MainWindow)
        self.ImageHub.setMinimumSize(QtCore.QSize(300, 65))
        self.ImageHub.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Image Hub", None, QtGui.QApplication.UnicodeUTF8))
        self.ImageHub.setObjectName(_fromUtf8("ImageHub"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setAutoFillBackground(False)
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Renders = renderViewer()
        self.Renders.setObjectName(_fromUtf8("Renders"))
        self.tabWidget.addTab(self.Renders, _fromUtf8(""))
        self.Dailies = dailiesViewer()
        self.Dailies.setObjectName(_fromUtf8("Dailies"))
        self.tabWidget.addTab(self.Dailies, _fromUtf8(""))
        self.Session = sessionViewer()
        self.Session.setObjectName(_fromUtf8("Session"))
        self.tabWidget.addTab(self.Session, _fromUtf8(""))
        self.Comment = commentViewer()
        self.Comment.setObjectName(_fromUtf8("Comment"))
        self.tabWidget.addTab(self.Comment, _fromUtf8(""))
        self.Queue = Queue()
        self.Queue.setObjectName(_fromUtf8("Queue"))
        self.tabWidget.addTab(self.Queue, _fromUtf8(""))
        self.Synch = QtGui.QWidget()
        self.Synch.setObjectName(_fromUtf8("Synch"))
        self.tabWidget.addTab(self.Synch, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.ImageHub.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.ImageHub)
        self.InfoViewer = QtGui.QDockWidget(MainWindow)
        self.InfoViewer.setMinimumSize(QtCore.QSize(600, 0))
        self.InfoViewer.setBaseSize(QtCore.QSize(100, 0))
        self.InfoViewer.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.InfoViewer.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Info Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.InfoViewer.setObjectName(_fromUtf8("InfoViewer"))
        self.Info = infoViewer()
        self.Info.setObjectName(_fromUtf8("Info"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Info)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, -1, 2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.InfoViewer.setWidget(self.Info)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.InfoViewer)
        self.commenetBrowserDoc = QtGui.QDockWidget(MainWindow)
        self.commenetBrowserDoc.setMinimumSize(QtCore.QSize(200, 111))
        self.commenetBrowserDoc.setFloating(False)
        self.commenetBrowserDoc.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Comments Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.commenetBrowserDoc.setObjectName(_fromUtf8("commenetBrowserDoc"))
        self.dockWidgetContents_5 = commentBrowser()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.commenetBrowserDoc.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.commenetBrowserDoc)
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setCheckable(True)
        self.actionFull_Screen.setText(QtGui.QApplication.translate("MainWindow", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionFull_Screen.setPriority(QtGui.QAction.NormalPriority)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.actionActual_Pixels = QtGui.QAction(MainWindow)
        self.actionActual_Pixels.setText(QtGui.QApplication.translate("MainWindow", "Actual_Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActual_Pixels.setShortcut(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActual_Pixels.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionActual_Pixels.setObjectName(_fromUtf8("actionActual_Pixels"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionNext_Frame = QtGui.QAction(MainWindow)
        self.actionNext_Frame.setCheckable(True)
        self.actionNext_Frame.setText(QtGui.QApplication.translate("MainWindow", "Next Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Frame.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Frame.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionNext_Frame.setObjectName(_fromUtf8("actionNext_Frame"))
        self.actionPrevious_Frame = QtGui.QAction(MainWindow)
        self.actionPrevious_Frame.setCheckable(True)
        self.actionPrevious_Frame.setText(QtGui.QApplication.translate("MainWindow", "Previous Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Frame.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Frame.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionPrevious_Frame.setObjectName(_fromUtf8("actionPrevious_Frame"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setAutoRepeat(False)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.menuFiles.addAction(self.actionImport)
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addAction(self.actionActual_Pixels)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionPlay)
        self.menuView.addAction(self.actionNext_Frame)
        self.menuView.addAction(self.actionPrevious_Frame)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.PlaypushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.playGL)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Renders), QtGui.QApplication.translate("MainWindow", "Renders ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dailies), QtGui.QApplication.translate("MainWindow", "For Review", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Session), QtGui.QApplication.translate("MainWindow", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Comment), QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Queue), QtGui.QApplication.translate("MainWindow", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Synch), QtGui.QApplication.translate("MainWindow", "Synch", None, QtGui.QApplication.UnicodeUTF8))

from dailiesViewer import dailiesViewer
from renderViewer import renderViewer
from infoViewer import infoViewer
from commentBrowser import commentBrowser
from colorCorrect import colorCorrect
from Queue import Queue
from commentViewer import commentViewer
from sessionviewer import sessionViewer
