# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renderViewer.ui'
#
# Created: Thu Dec 08 23:07:28 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1567, 616)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setText(QtGui.QApplication.translate("Form", " Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 7, 1, 1)
        self.SequComboBox = QtGui.QComboBox(self.frame)
        self.SequComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SequComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.SequComboBox.setObjectName(_fromUtf8("SequComboBox"))
        self.gridLayout.addWidget(self.SequComboBox, 1, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 9, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setText(QtGui.QApplication.translate("Form", " Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 10, 1, 1)
        self.ShotComboBox = QtGui.QComboBox(self.frame)
        self.ShotComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ShotComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.ShotComboBox.setObjectName(_fromUtf8("ShotComboBox"))
        self.gridLayout.addWidget(self.ShotComboBox, 1, 11, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 12, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Hide submitted", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 1, 16, 1, 1)
        self.TypeComboBox = QtGui.QComboBox(self.frame)
        self.TypeComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TypeComboBox.setObjectName(_fromUtf8("TypeComboBox"))
        self.gridLayout.addWidget(self.TypeComboBox, 1, 14, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 13, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 15, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(0, 0, 10, 0)
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.filterLabel = QtGui.QLabel(self.frame_2)
        self.filterLabel.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.filterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filterLabel.setObjectName(_fromUtf8("filterLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.filterLabel)
        self.filterLineEdit = QtGui.QLineEdit(self.frame_2)
        self.filterLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.filterLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filterLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.filterLineEdit.setObjectName(_fromUtf8("filterLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.filterLineEdit)
        self.gridLayout.addWidget(self.frame_2, 1, 18, 1, 1)
        self.refreshCombosPB = QtGui.QPushButton(self.frame)
        self.refreshCombosPB.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshCombosPB.setObjectName(_fromUtf8("refreshCombosPB"))
        self.gridLayout.addWidget(self.refreshCombosPB, 1, 20, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.frame)
        self.radioButton_2.setText(QtGui.QApplication.translate("Form", "Hide Archived", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 1, 17, 1, 1)
        self.toolButton = QtGui.QToolButton(self.frame)
        self.toolButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 1, 19, 1, 1)
        self.ProjectComboBox = QtGui.QComboBox(self.frame)
        self.ProjectComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ProjectComboBox.setEditable(False)
        self.ProjectComboBox.setFrame(False)
        self.ProjectComboBox.setObjectName(_fromUtf8("ProjectComboBox"))
        self.gridLayout.addWidget(self.ProjectComboBox, 1, 5, 1, 1)
        self.UserComboBox = QtGui.QComboBox(self.frame)
        self.UserComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.UserComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.UserComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.UserComboBox.setObjectName(_fromUtf8("UserComboBox"))
        self.gridLayout.addWidget(self.UserComboBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setText(QtGui.QApplication.translate("Form", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.list = QtGui.QTreeWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list.sizePolicy().hasHeightForWidth())
        self.list.setSizePolicy(sizePolicy)
        self.list.setMinimumSize(QtCore.QSize(400, 0))
        self.list.setFrameShape(QtGui.QFrame.StyledPanel)
        self.list.setFrameShadow(QtGui.QFrame.Plain)
        self.list.setLineWidth(0)
        self.list.setAutoScroll(False)
        self.list.setTabKeyNavigation(False)
        self.list.setAlternatingRowColors(True)
        self.list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list.setRootIsDecorated(True)
        self.list.setUniformRowHeights(True)
        self.list.setAnimated(True)
        self.list.setAllColumnsShowFocus(False)
        self.list.setWordWrap(True)
        self.list.setExpandsOnDoubleClick(False)
        self.list.setObjectName(_fromUtf8("list"))
        self.list.headerItem().setText(0, QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(1, QtGui.QApplication.translate("Form", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(2, QtGui.QApplication.translate("Form", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(3, QtGui.QApplication.translate("Form", "Out", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(4, QtGui.QApplication.translate("Form", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(5, QtGui.QApplication.translate("Form", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(6, QtGui.QApplication.translate("Form", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(7, QtGui.QApplication.translate("Form", "User/Node", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(8, QtGui.QApplication.translate("Form", "Date modified", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(9, QtGui.QApplication.translate("Form", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(10, QtGui.QApplication.translate("Form", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setText(11, QtGui.QApplication.translate("Form", "Scene file", None, QtGui.QApplication.UnicodeUTF8))
        self.list.headerItem().setTextAlignment(11, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.list.header().setCascadingSectionResizes(False)
        self.list.header().setDefaultSectionSize(50)
        self.list.header().setHighlightSections(True)
        self.list.header().setMinimumSectionSize(40)
        self.list.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.list)
        self.frame_3 = QtGui.QFrame(self.widget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setContentsMargins(0, 0, 40, 0)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Thumbnail scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.thumbScale = QtGui.QSlider(self.frame_3)
        self.thumbScale.setMaximumSize(QtCore.QSize(300, 16777215))
        self.thumbScale.setOrientation(QtCore.Qt.Horizontal)
        self.thumbScale.setObjectName(_fromUtf8("thumbScale"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.thumbScale)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.widget_2 = QtGui.QWidget(self.splitter)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LoadGroupBox = QtGui.QGroupBox(self.widget_2)
        self.LoadGroupBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.LoadGroupBox.setTitle(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadGroupBox.setObjectName(_fromUtf8("LoadGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.LoadGroupBox)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.LoadPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadPushButton.setText(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadPushButton.setObjectName(_fromUtf8("LoadPushButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LoadPushButton)
        self.LoadFpPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadFpPushButton.setText(QtGui.QApplication.translate("Form", "LOAD_FP", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadFpPushButton.setObjectName(_fromUtf8("LoadFpPushButton"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LoadFpPushButton)
        self.DiskCachePushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.DiskCachePushButton.setText(QtGui.QApplication.translate("Form", "Make Disk Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.DiskCachePushButton.setObjectName(_fromUtf8("DiskCachePushButton"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.DiskCachePushButton)
        self.LoadProxPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadProxPushButton.setText(QtGui.QApplication.translate("Form", "LOAD Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadProxPushButton.setObjectName(_fromUtf8("LoadProxPushButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LoadProxPushButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem5)
        self.useDiskCacheRadioButton = QtGui.QRadioButton(self.LoadGroupBox)
        self.useDiskCacheRadioButton.setText(QtGui.QApplication.translate("Form", "use disk cache", None, QtGui.QApplication.UnicodeUTF8))
        self.useDiskCacheRadioButton.setObjectName(_fromUtf8("useDiskCacheRadioButton"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.useDiskCacheRadioButton)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.LoadGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "SUBMIT", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.submitDailiesPushButton = QtGui.QPushButton(self.groupBox_2)
        self.submitDailiesPushButton.setText(QtGui.QApplication.translate("Form", "Submit for review", None, QtGui.QApplication.UnicodeUTF8))
        self.submitDailiesPushButton.setObjectName(_fromUtf8("submitDailiesPushButton"))
        self.verticalLayout_5.addWidget(self.submitDailiesPushButton)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Submit to comp", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "MANAGE FILES", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setContentsMargins(0, 2, 2, 2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.ArchivePushButton = QtGui.QPushButton(self.groupBox_3)
        self.ArchivePushButton.setText(QtGui.QApplication.translate("Form", "Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.ArchivePushButton.setObjectName(_fromUtf8("ArchivePushButton"))
        self.verticalLayout_6.addWidget(self.ArchivePushButton)
        self.DeleteRenderPushButton = QtGui.QPushButton(self.groupBox_3)
        self.DeleteRenderPushButton.setText(QtGui.QApplication.translate("Form", "Delete Render", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteRenderPushButton.setObjectName(_fromUtf8("DeleteRenderPushButton"))
        self.verticalLayout_6.addWidget(self.DeleteRenderPushButton)
        self.DeleteFilesOnly = QtGui.QPushButton(self.groupBox_3)
        self.DeleteFilesOnly.setText(QtGui.QApplication.translate("Form", "Delete Files Only", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteFilesOnly.setObjectName(_fromUtf8("DeleteFilesOnly"))
        self.verticalLayout_6.addWidget(self.DeleteFilesOnly)
        self.CopyToServerPushButton = QtGui.QPushButton(self.groupBox_3)
        self.CopyToServerPushButton.setText(QtGui.QApplication.translate("Form", "Copy To Server", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyToServerPushButton.setObjectName(_fromUtf8("CopyToServerPushButton"))
        self.verticalLayout_6.addWidget(self.CopyToServerPushButton)
        self.MakeLocalPushButton = QtGui.QPushButton(self.groupBox_3)
        self.MakeLocalPushButton.setText(QtGui.QApplication.translate("Form", "Make Local", None, QtGui.QApplication.UnicodeUTF8))
        self.MakeLocalPushButton.setObjectName(_fromUtf8("MakeLocalPushButton"))
        self.verticalLayout_6.addWidget(self.MakeLocalPushButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.LoadPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.Load)
        QtCore.QObject.connect(self.submitDailiesPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.submitDailie)
        QtCore.QObject.connect(self.refreshCombosPB, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.refreshCombos)
        QtCore.QObject.connect(self.LoadFpPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.LoadFP)
        QtCore.QObject.connect(self.LoadProxPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.LoadProxy)
        QtCore.QObject.connect(self.DiskCachePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.makeDiskCache)
        QtCore.QObject.connect(self.ArchivePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.Archive)
        QtCore.QObject.connect(self.DeleteRenderPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.deleteRender)
        QtCore.QObject.connect(self.DeleteFilesOnly, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.deleFilesOnly)
        QtCore.QObject.connect(self.filterLineEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), Form.Search)
        QtCore.QObject.connect(self.list, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), Form.updateInfo)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.list.setSortingEnabled(True)

