# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionViewer.ui'
#
# Created: Thu Sep 08 00:21:01 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1263, 647)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_10 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setMargin(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.refreshDB_pushButton = QtGui.QPushButton(self.frame)
        self.refreshDB_pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.refreshDB_pushButton.setText(QtGui.QApplication.translate("Form", "RefreshDB", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshDB_pushButton.setObjectName(_fromUtf8("refreshDB_pushButton"))
        self.horizontalLayout.addWidget(self.refreshDB_pushButton)
        self.widget_6 = QtGui.QWidget(self.frame)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout.addWidget(self.widget_6)
        self.verticalLayout_7.addWidget(self.frame)
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.splitter_2 = QtGui.QSplitter(self.widget_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget_4 = QtGui.QWidget(self.splitter_2)
        self.widget_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SessionSelectTreeWidget = QtGui.QTreeWidget(self.widget_4)
        self.SessionSelectTreeWidget.setTabKeyNavigation(True)
        self.SessionSelectTreeWidget.setAlternatingRowColors(True)
        self.SessionSelectTreeWidget.setItemsExpandable(False)
        self.SessionSelectTreeWidget.setAnimated(True)
        self.SessionSelectTreeWidget.setAllColumnsShowFocus(True)
        self.SessionSelectTreeWidget.setWordWrap(True)
        self.SessionSelectTreeWidget.setObjectName(_fromUtf8("SessionSelectTreeWidget"))
        self.SessionSelectTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "Session Name", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionSelectTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "date", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_3.addWidget(self.SessionSelectTreeWidget)
        self.widget_5 = QtGui.QWidget(self.splitter_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.SessionTimeLine = QtGui.QTreeWidget(self.widget_5)
        self.SessionTimeLine.setTabKeyNavigation(True)
        self.SessionTimeLine.setDragEnabled(True)
        self.SessionTimeLine.setDragDropOverwriteMode(False)
        self.SessionTimeLine.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.SessionTimeLine.setAlternatingRowColors(True)
        self.SessionTimeLine.setUniformRowHeights(True)
        self.SessionTimeLine.setItemsExpandable(False)
        self.SessionTimeLine.setAnimated(True)
        self.SessionTimeLine.setAllColumnsShowFocus(True)
        self.SessionTimeLine.setObjectName(_fromUtf8("SessionTimeLine"))
        self.SessionTimeLine.headerItem().setText(0, QtGui.QApplication.translate("Form", "Dailie Name", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(1, QtGui.QApplication.translate("Form", "Load Status", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(2, QtGui.QApplication.translate("Form", "In", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(3, QtGui.QApplication.translate("Form", "Out", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(4, QtGui.QApplication.translate("Form", "Cut In", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(5, QtGui.QApplication.translate("Form", "Cut Out", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionTimeLine.headerItem().setText(6, QtGui.QApplication.translate("Form", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_6.addWidget(self.SessionTimeLine)
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.LoadGroupBox = QtGui.QGroupBox(self.widget_2)
        self.LoadGroupBox.setMaximumSize(QtCore.QSize(16777215, 16775))
        self.LoadGroupBox.setTitle(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadGroupBox.setObjectName(_fromUtf8("LoadGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.LoadGroupBox)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.LoadPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadPushButton.setText(QtGui.QApplication.translate("Form", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadPushButton.setObjectName(_fromUtf8("LoadPushButton"))
        self.verticalLayout_4.addWidget(self.LoadPushButton)
        self.LoadFpPushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.LoadFpPushButton.setText(QtGui.QApplication.translate("Form", "LOAD_FP", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadFpPushButton.setObjectName(_fromUtf8("LoadFpPushButton"))
        self.verticalLayout_4.addWidget(self.LoadFpPushButton)
        self.DiskCachePushButton = QtGui.QPushButton(self.LoadGroupBox)
        self.DiskCachePushButton.setText(QtGui.QApplication.translate("Form", "DISK CACHE", None, QtGui.QApplication.UnicodeUTF8))
        self.DiskCachePushButton.setObjectName(_fromUtf8("DiskCachePushButton"))
        self.verticalLayout_4.addWidget(self.DiskCachePushButton)
        self.pushButton_2 = QtGui.QPushButton(self.LoadGroupBox)
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "LOAD PROXY", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LoadGroupBox)
        self.SessionGroupbox = QtGui.QGroupBox(self.widget_2)
        self.SessionGroupbox.setTitle(QtGui.QApplication.translate("Form", "CREATE", None, QtGui.QApplication.UnicodeUTF8))
        self.SessionGroupbox.setObjectName(_fromUtf8("SessionGroupbox"))
        self.formLayout_2 = QtGui.QFormLayout(self.SessionGroupbox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.pushButton = QtGui.QPushButton(self.SessionGroupbox)
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Create new session", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButton)
        self.dateEdit = QtGui.QDateEdit(self.SessionGroupbox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.dateEdit)
        self.lineEdit = QtGui.QLineEdit(self.SessionGroupbox)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lineEdit)
        self.label = QtGui.QLabel(self.SessionGroupbox)
        self.label.setText(QtGui.QApplication.translate("Form", "session name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.SessionGroupbox)
        self.groupBox = QtGui.QGroupBox(self.widget_2)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "DataBase", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_7.addWidget(self.widget)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.refreshDB_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.refreshCal)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.SessionSelectTreeWidget.setSortingEnabled(True)
        self.SessionTimeLine.setSortingEnabled(False)

